In [116]:
import pandas as pd 
import numpy as np

In [117]:
df=pd.read_csv("C:\\Users\\bless\\OneDrive\\Documents\\survey lung cancer.csv")
df.head()

GENDER  AGE  SMOKING  YELLOW_FINGERS  ANXIETY  PEER_PRESSURE  \
0      M   69        1               2        2              1   
1      M   74        2               1        1              1   
2      F   59        1               1        1              2   
3      M   63        2               2        2              1   
4      F   63        1               2        1              1   

   CHRONIC DISEASE  FATIGUE   ALLERGY   WHEEZING  ALCOHOL CONSUMING  COUGHING  \
0                1         2         1         2                  2         2   
1                2         2         2         1                  1         1   
2                1         2         1         2                  1         2   
3                1         1         1         1                  2         1   
4                1         1         1         2                  1         2   

   SHORTNESS OF BREATH  SWALLOWING DIFFICULTY  CHEST PAIN LUNG_CANCER  
0                    2                      2           2         YES  
1                    2                      2           2         YES  
2                    2                      1           2          NO  
3                    1                      2           2          NO  
4                    2                      1           1          NO

In [118]:
df.columns

Index(['GENDER', 'AGE', 'SMOKING', 'YELLOW_FINGERS', 'ANXIETY',
       'PEER_PRESSURE', 'CHRONIC DISEASE', 'FATIGUE ', 'ALLERGY ', 'WHEEZING',
       'ALCOHOL CONSUMING', 'COUGHING', 'SHORTNESS OF BREATH',
       'SWALLOWING DIFFICULTY', 'CHEST PAIN', 'LUNG_CANCER'],
      dtype='object')

In [119]:
df.shape

(309, 16)

In [120]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 309 entries, 0 to 308
Data columns (total 16 columns):
 #   Column                 Non-Null Count  Dtype 
---  ------                 --------------  ----- 
 0   GENDER                 309 non-null    object
 1   AGE                    309 non-null    int64 
 2   SMOKING                309 non-null    int64 
 3   YELLOW_FINGERS         309 non-null    int64 
 4   ANXIETY                309 non-null    int64 
 5   PEER_PRESSURE          309 non-null    int64 
 6   CHRONIC DISEASE        309 non-null    int64 
 7   FATIGUE                309 non-null    int64 
 8   ALLERGY                309 non-null    int64 
 9   WHEEZING               309 non-null    int64 
 10  ALCOHOL CONSUMING      309 non-null    int64 
 11  COUGHING               309 non-null    int64 
 12  SHORTNESS OF BREATH    309 non-null    int64 
 13  SWALLOWING DIFFICULTY  309 non-null    int64 
 14  CHEST PAIN             309 non-null    int64 
 15  LUNG_CANCER            

In [121]:
df.describe()

AGE     SMOKING  YELLOW_FINGERS     ANXIETY  PEER_PRESSURE  \
count  309.000000  309.000000      309.000000  309.000000     309.000000   
mean    62.673139    1.563107        1.569579    1.498382       1.501618   
std      8.210301    0.496806        0.495938    0.500808       0.500808   
min     21.000000    1.000000        1.000000    1.000000       1.000000   
25%     57.000000    1.000000        1.000000    1.000000       1.000000   
50%     62.000000    2.000000        2.000000    1.000000       2.000000   
75%     69.000000    2.000000        2.000000    2.000000       2.000000   
max     87.000000    2.000000        2.000000    2.000000       2.000000   

       CHRONIC DISEASE    FATIGUE     ALLERGY     WHEEZING  ALCOHOL CONSUMING  \
count       309.000000  309.000000  309.000000  309.000000         309.000000   
mean          1.504854    1.673139    1.556634    1.556634           1.556634   
std           0.500787    0.469827    0.497588    0.497588           0.497588   
min           1.000000    1.000000    1.000000    1.000000           1.000000   
25%           1.000000    1.000000    1.000000    1.000000           1.000000   
50%           2.000000    2.000000    2.000000    2.000000           2.000000   
75%           2.000000    2.000000    2.000000    2.000000           2.000000   
max           2.000000    2.000000    2.000000    2.000000           2.000000   

         COUGHING  SHORTNESS OF BREATH  SWALLOWING DIFFICULTY  CHEST PAIN  
count  309.000000           309.000000             309.000000  309.000000  
mean     1.579288             1.640777               1.469256    1.556634  
std      0.494474             0.480551               0.499863    0.497588  
min      1.000000             1.000000               1.000000    1.000000  
25%      1.000000             1.000000               1.000000    1.000000  
50%      2.000000             2.000000               1.000000    2.000000  
75%      2.000000             2.000000               2.000000    2.000000  
max      2.000000             2.000000               2.000000    2.000000

In [122]:
df.isnull().sum()

GENDER                   0
AGE                      0
SMOKING                  0
YELLOW_FINGERS           0
ANXIETY                  0
PEER_PRESSURE            0
CHRONIC DISEASE          0
FATIGUE                  0
ALLERGY                  0
WHEEZING                 0
ALCOHOL CONSUMING        0
COUGHING                 0
SHORTNESS OF BREATH      0
SWALLOWING DIFFICULTY    0
CHEST PAIN               0
LUNG_CANCER              0
dtype: int64

In [123]:
from sklearn.preprocessing import LabelEncoder
label_encoder=LabelEncoder()
categorical_columns=['GENDER','LUNG_CANCER']
df[categorical_columns]=df[categorical_columns].apply(label_encoder.fit_transform)
df[categorical_columns]

GENDER  LUNG_CANCER
0         1            1
1         1            1
2         0            0
3         1            0
4         0            0
..      ...          ...
304       0            1
305       1            1
306       1            1
307       1            1
308       1            1

[309 rows x 2 columns]

In [124]:
x=df.iloc[:,:-1]
x

GENDER  AGE  SMOKING  YELLOW_FINGERS  ANXIETY  PEER_PRESSURE  \
0         1   69        1               2        2              1   
1         1   74        2               1        1              1   
2         0   59        1               1        1              2   
3         1   63        2               2        2              1   
4         0   63        1               2        1              1   
..      ...  ...      ...             ...      ...            ...   
304       0   56        1               1        1              2   
305       1   70        2               1        1              1   
306       1   58        2               1        1              1   
307       1   67        2               1        2              1   
308       1   62        1               1        1              2   

     CHRONIC DISEASE  FATIGUE   ALLERGY   WHEEZING  ALCOHOL CONSUMING  \
0                  1         2         1         2                  2   
1                  2         2         2         1                  1   
2                  1         2         1         2                  1   
3                  1         1         1         1                  2   
4                  1         1         1         2                  1   
..               ...       ...       ...       ...                ...   
304                2         2         1         1                  2   
305                1         2         2         2                  2   
306                1         1         2         2                  2   
307                1         2         2         1                  2   
308                1         2         2         2                  2   

     COUGHING  SHORTNESS OF BREATH  SWALLOWING DIFFICULTY  CHEST PAIN  
0           2                    2                      2           2  
1           1                    2                      2           2  
2           2                    2                      1           2  
3           1                    1                      2           2  
4           2                    2                      1           1  
..        ...                  ...                    ...         ...  
304         2                    2                      2           1  
305         2                    2                      1           2  
306         2                    1                      1           2  
307         2                    2                      1           2  
308         1                    1                      2           1  

[309 rows x 15 columns]

In [125]:
y=df.iloc[:,-1]
y

0      1
1      1
2      0
3      0
4      0
      ..
304    1
305    1
306    1
307    1
308    1
Name: LUNG_CANCER, Length: 309, dtype: int32

In [126]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [127]:
x_train.shape

(247, 15)

In [128]:
x_test.shape

(62, 15)

In [129]:
y_train.shape

(247,)

In [130]:
y_test.shape

(62,)

In [131]:
from sklearn.svm import SVC
sv=SVC()

In [132]:
sv.fit(x_train,y_train)

SVC()

In [133]:
y_pred=sv.predict(x_test)
y_pred

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [134]:
from sklearn.metrics import accuracy_score
accuracy=accuracy_score(y_pred,y_test)
print("Accuracy of the model is {:.2f}".format(accuracy))

Accuracy of the model is 0.84


In [135]:
from sklearn.tree import DecisionTreeClassifier
model=DecisionTreeClassifier()

In [136]:
model.fit(x,y)

DecisionTreeClassifier()

In [137]:
y_pred=model.predict(x_test)
y_pred

array([1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1,
       1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1])

In [138]:
from sklearn.metrics import accuracy_score
accuracy=accuracy_score(y_pred,y_test)
print("Accuracy of the model is {:.2f}".format(accuracy))

Accuracy of the model is 1.00


In [139]:
from sklearn.neighbors import KNeighborsClassifier
kn=KNeighborsClassifier(n_neighbors=6)

In [140]:
kn.fit(x_train,y_train)

KNeighborsClassifier(n_neighbors=6)

In [141]:
y_pred=kn.predict(x_test)
y_pred

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [142]:
from sklearn.metrics import accuracy_score
accuracy=accuracy_score(y_pred,y_test)
print("Accuracy of the model is {:.2f}".format(accuracy))

Accuracy of the model is 0.84


In [143]:
from sklearn.naive_bayes import GaussianNB
nv=GaussianNB()

In [144]:
nv.fit(x_train,y_train)

GaussianNB()

In [145]:
y_pred=nv.predict(x_test)
y_pred

array([1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1,
       1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [146]:
from sklearn.metrics import accuracy_score
accuracy=accuracy_score(y_pred,y_test)
print("Accuracy of the model is {:.2f}".format(accuracy))

Accuracy of the model is 0.87


In [147]:
from sklearn.ensemble import GradientBoostingClassifier
gb=GradientBoostingClassifier()

In [148]:
gb.fit(x_train,y_train)

GradientBoostingClassifier()

In [149]:
y_pred=gb.predict(x_test)
y_pred

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1])

In [150]:
from sklearn.metrics import accuracy_score
accuracy=accuracy_score(y_pred,y_test)
print("Accuracy of the model is {:.2f}".format(accuracy))

Accuracy of the model is 0.90


In [151]:
from sklearn.ensemble import RandomForestClassifier
rf=RandomForestClassifier()

In [152]:
rf.fit(x_train,y_train)

RandomForestClassifier()

In [153]:
y_pred=rf.predict(x_test)
y_pred

array([1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1,
       1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1])

In [154]:
from sklearn.metrics import accuracy_score
accuracy=accuracy_score(y_pred,y_test)
print("Accuracy of the model is {:.2f}".format(accuracy))

Accuracy of the model is 0.95


In [155]:
from sklearn.ensemble import AdaBoostClassifier
ab=AdaBoostClassifier()

In [156]:
ab.fit(x_train,y_train)

C:\Users\bless\anaconda3\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:519: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(


AdaBoostClassifier()

In [157]:
y_pred=ab.predict(x_test)
y_pred

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1])

In [158]:
from sklearn.metrics import accuracy_score
accuracy=accuracy_score(y_pred,y_test)
print("Accuracy of the model is {:.2f}".format(accuracy))

Accuracy of the model is 0.92


In [159]:
!pip install catboost

In [160]:
from catboost import CatBoostClassifier
cb=CatBoostClassifier(iterations=5,learning_rate=0.1)

In [161]:
cb.fit(x_train,y_train)

0:	learn: 0.6675092	total: 1.71ms	remaining: 6.84ms
1:	learn: 0.6185792	total: 3.06ms	remaining: 4.59ms
2:	learn: 0.5965271	total: 4.06ms	remaining: 2.71ms
3:	learn: 0.5715116	total: 5.23ms	remaining: 1.31ms
4:	learn: 0.5450521	total: 6.42ms	remaining: 0us


In [162]:
y_pred=ab.predict(x_test)
y_pred

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1])

In [163]:
from sklearn.metrics import accuracy_score
accuracy=accuracy_score(y_pred,y_test)
print("Accuracy of the model is {:.2f}".format(accuracy))

Accuracy of the model is 0.92


In [164]:
!pip install xgboost

In [165]:
from xgboost import XGBClassifier
xg=XGBClassifier(n_estimators=2)

In [166]:
xg.fit(x_train,y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=2, n_jobs=None,
              num_parallel_tree=None, random_state=None, ...)

In [167]:
y_pred=xg.predict(x_test)
y_pred

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [168]:
from sklearn.metrics import accuracy_score
accuracy=accuracy_score(y_pred,y_test)
print("Accuracy of the model is {:.2f}".format(accuracy))

Accuracy of the model is 0.84


In [169]:
new_data=[1,74,2,1,1,1,2,2,2,1,1,1,2,2,2]
predictions=model.predict([new_data])
print(predictions)

[1]


C:\Users\bless\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


In [170]:
decoded_predictions=label_encoder.inverse_transform(predictions)
print(decoded_predictions)

['YES']
